#!/usr/bin/env ruby

require 'rubygems'
require 'ruby-debug'

require File.expand_path(__FILE__ + "/../../config/environment")
require "#{RAILS_ROOT}/lib/tagger"

user = User.find_by_name "deepbondi"
playlist = Playlist.new
playlist.user = user
playlist.name = "bootstrapped"
playlist.save
songs = (Song.all :limit => 50)
songs.each do |song|
    playlist.plentries.push Plentry.new({:song=>song})
end

playlist.active = true
playlist.save