#!/usr/bin/env ruby

require 'rubygems'
require 'ruby-debug'

puts "This will completely wipe your database of all songs,playlists,artist, etc are you absolutely sure?\nType \"yes\" to continue."
answer = gets().upcase.chomp

exit unless answer == "YES"

require File.expand_path(__FILE__ + "/../../config/environment")
require "#{RAILS_ROOT}/lib/tagger"

puts "Destroying songs"
things = Song.all
things.each do |song|
    song.destroy
end

puts "Destroying playlist entries"
things = Plentry.all
things.each do |entry|
    entry.destroy
end

puts "Destroying playlists"
things = Playlist.all
things.each do |playlist|
    playlist.destroy
end

puts "Destroying albums"
things = Album.all
things.each do |album|
    album.destroy
end

puts "Destroying artists"
things = Artist.all
things.each do |artist|
    artist.destroy
end

puts "Destroying genres"
things = Genre.all
things.each do |genre|
    genre.destroy
end
