#!/usr/bin/env ruby

require 'find'
require 'ruby-debug'

DEFAULT_PATH = "/Volumes/MajorTuneage/"

RAILS_ENV="production"


old = ARGV.shift
new = ARGV.shift
test = ARGV.shift


if old == "--help"
    puts "Usage:"
    puts "./script/mvsong \"/fully/qualifed/path/to/old/file\" \"/fully/qualified/path/to/new/file\""
    puts "Note: You should quote your path names to use this utility"
    exit
end

unless( FileTest.file?(old))
    raise "Specified file: #{old}. Does not exist."
end

if ( FileTest.file?(new))
    raise "There is something at the specified move to location. That is no good"
end

unless ((old.include? DEFAULT_PATH) && (new.include? DEFAULT_PATH))
    raise "You specified files outside of our default path. You Specified:
#{old}
#{new}" 
end

if (test)
    raise "WTF is #{test}? Do you know what you are doing? Or do you just need to quote your paths?"
end

require File.expand_path(__FILE__ + "/../../config/environment")

song = Song.find_by_file old

if song
    pastpath = song.pastpaths.build :attributes => {:file => song.file}
    pastpath.save
    directories = old.split("/")
    directories.shift
    directories.pop
    rebuild = ""
    directories.each do |dir|
        rebuild += ("/" + dir)
        (raise "there is a real file in that path!!!") if (FileTest.file?(rebuild))
        unless (FileTest.directory?(rebuild))
                puts rebuild
            system "mkdir #{rebuild}"
        end
    end
    system "mv #{old} #{new}"
    song.file = new
    song.save
    if ( (FileTest.file?(song.file)) && !(FileTest.file?(old)) )
        puts "Everything looks good"
    end
else
    puts "Couldn't find your song: #{old}. Sumthin' musta happend to it man."
end
